---
apiVersion: tf.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: aws-us-east-1
  namespace : crossplane-system
spec:
  credentials:
  - filename: aws-creds.ini
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: credentials
  - filename: .git-credentials # use exactly this filename
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: git-credentials
      key: .git-credentials
  configuration: |
      terraform {
        backend "kubernetes" {
          secret_suffix     = "providerconfig-aws-us-east-1"
          namespace         = "crossplane-system"
          in_cluster_config = true
        }
      }
      provider "aws" {
        shared_credentials_file = "aws-creds.ini"
        region = "us-east-1"
      }
      